---
- name: Install WordPress, MariaDB, Nginx, and PHP-FPM
  hosts: targets
  remote_user: rainbow
  become_user: rainbow
  become: yes
  roles:
    # - common
    # - mariadb
    # - nginx
    - dev_env
    # - php-fpm
    # - wordpress
