---
- name: Install vim
  yum: name=vim state=present

- name: Install tmux
  yum: name=tmux state=present

- name: Install git
  yum: name=git state=present

- name: Install zsh
  yum: name=zsh state=present

- name: Install autojump
  git:
    repo: 'https://github.com/wting/autojump.git'
    dest: /home/rainbow/autojump
    clone: yes
    update: yes

# module error 後回し
# - name: Install autojump
#   shell: /home/rainbow/autojump/install.py
#   args:
#     executable: /bin/bash

- name: Install dotfiles
  git:
    repo: 'https://github.com/rainbow23/dotfiles.git'
    dest: /home/rainbow/dotfiles

    force: yes
    update: yes

- name: Permission change dotfiles
  file:
    path: /home/rainbow/dotfiles
    owner: rainbow
    group: wheel
    mode: 0755
    recurse: true
    state: directory

- name: Create symlink .vimrc
  file:
    src: /home/rainbow/dotfiles/_vimrc
    dest: /home/rainbow/.vimrc
    owner: rainbow
    group: wheel
    mode: 0755
    state: link

# dest dir がないとでるので後回し
# - name: Install vim-plug
#   get_url:
#     url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
#     dest: /home/rainbow/.vim/autoload/plug.vim
#     mode: 0755
#     owner: rainbow

