---
- name: Install vim
  yum: name=vim state=present

- name: Install tmux
  yum: name=tmux state=present

- name: Install git
  yum: name=git state=present

- name: Install zsh
  yum: name=zsh state=present

# - name: Install autojump
- git:
    repo: 'https://github.com/wting/autojump.git'
    # dest: /tmp/autojump
    dest: /home/rainbow/autojump
    clone: yes
    update: yes

# - name: Install autojump
#   shell: /home/rainbow/autojump/install.py
#   args:
#     executable: /bin/bash

- name: Install vim-plug
  shell: curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  args:
    executable: /bin/bash

# - name: Install dotfiles
- git:
    repo: 'https://github.com/rainbow23/dotfiles.git'
    dest: /home/rainbow/dotfiledotfilesnel]s
    clone: yes
    update: yes
