---
- name: "Install packages"
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - vim-enhanced
    - tmux
    - git
    - zsh

- name: autojumpディレクトリの存在チェック
  stat:
    path: "/home/{{ ansible_user }}/autojump"
  register: fm

- name: Clone autojump
  git:
    repo: 'https://github.com/wting/autojump.git'
    dest: "/home/{{ ansible_user }}/autojump"
    clone: yes
    update: yes
  become_user: "{{ ansible_user }}"
  when: not fm.stat.exists

- name: Permission change autojump directory
  file:
    path: "/home/{{ ansible_user }}/autojump"
    owner: "{{ ansible_user }}"
    group: wheel
    mode: 0755
    recurse: true
    state: directory

- name: Install autojump
  shell: "cd /home/{{ ansible_user }}/autojump && ./install.py"
  args:
    executable: /bin/bash
  become_user: "{{ ansible_user }}"

- name: Clone dotfiles
  git:
    repo: 'https://github.com/rainbow23/dotfiles.git'
    dest: "/home/{{ ansible_user }}/dotfiles"
    force: yes
    update: yes
  become_user: "{{ ansible_user }}"

- name: Permission change dotfiles directory
  file:
    path: "/home/{{ ansible_user }}/dotfiles"
    owner: "{{ ansible_user }}"
    group: wheel
    mode: 0755
    recurse: true
    state: directory

- name: .bashrcディレクトリの存在チェック
  stat:
    path: "/home/{{ ansible_user }}/.bashrc"
  register: bc

- name: Delete file at .bashrc
  file:
    path: "/home/{{ ansible_user }}/.bashrc"
    state: absent
  when: bc.stat.exists == True

- name: Create symlink
  file:
    src: "/home/{{ ansible_user }}/dotfiles/_{{ item }}"
    dest: "/home/{{ ansible_user }}/.{{ item }}"
    owner: "{{ ansible_user }}"
    group: wheel
    mode: 0755
    state: link
  with_items:
    - vimrc
    - bashrc
    - zshrc
    - tmux.conf

- name: Create Directory
  file:
    path: "/home/{{ ansible_user }}/.vim/autoload"
    owner: "{{ ansible_user }}"
    group: wheel
    mode: 0755
    state: directory

- name: Install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "/home/{{ ansible_user }}/.vim/autoload/plug.vim"
    mode: 0755
    owner: "{{ ansible_user }}"

