---
- name: "Set vars"
  set_fact:
    home_path: "/home/{{ ansible_user }}"
    base_clone_path: "https://github.com"
    go_version: "1.8.3"

- name: "Install packages"
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - gcc
    - lua-devel
    - perl-ExtUtils-Embed
    - zlib-devel
    - bzip2
    - bzip2-devel
    - readline-devel
    - sqlite
    - sqlite-devel
    - openssl-devel
    - tmux
    - git
    - zsh
    - tree

- name: Clone repository
  git:
    repo: "{{ item.path }}"
    dest: "{{ home_path }}/{{ item.dir }}"
    force: yes
    update: yes
    # update: no
  become_user: "{{ ansible_user }}"
  with_items:
    - { path: "{{ base_clone_path }}/wting/autojump.git",     dir: "autojump" }
    - { path: "{{ base_clone_path }}/rainbow23/dotfiles.git", dir: "dotfiles" }
    - { path: "{{ base_clone_path }}/tmux/tmux.git",          dir: "tmuxsrc" }
    - { path: "{{ base_clone_path }}/tmux-plugins/tpm",       dir: ".tmux/plugins/tpm" }
    - { path: "{{ base_clone_path }}/vim/vim",                dir: "vim8src" }
    - { path: "{{ base_clone_path }}/riywo/anyenv",           dir: ".anyenv" }
  notify:
    - Permission change to directories
    - Install autojump
    - Install pyenv from source
    - Compile Vim
    - Install goenv
    - Install go
    - Delete cloned directories

- block:
  - name: .bashrcディレクトリの存在チェック
    stat:
      path: "{{ home_path }}/.bashrc"
    register: bc
  - name: Delete file at .bashrc
    file:
      path: "{{ home_path }}/.bashrc"
      state: absent
    when: bc.stat.exists == True
  - name: Create symlink
    file:
      src: "{{ home_path }}/dotfiles/_{{ item }}"
      dest: "{{ home_path }}/.{{ item }}"
      owner: "{{ ansible_user }}"
      group: wheel
      mode: 0755
      state: link
    with_items:
      - vimrc
      - bashrc
      - zshrc
      - tmux.conf

- block:
  - name: add anyenv path to .bashrc and .zshrc
    shell: |
      echo -e '\n# anyenv' >> {{ item }}
      echo 'if [ -d $HOME/.anyenv ] ; then' >> {{ item }}
      echo '    export PATH="$HOME/.anyenv/bin:$PATH"' >>  {{ item }}
      echo '    eval "$(anyenv init -)"' >>  {{ item }}
      echo 'fi' >>  {{ item }}
      exec $SHELL -l
    with_items:
      - ~/.bashrc
      - ~/.zshrc
    become_user: "{{ ansible_user }}"

- block:
  - name: .vim/autoloadディレクトリの存在チェック
    stat:
      path: "{{ home_path }}/.vim/autoload/"
    register: vim_path
  - name: Create vim-plug folder
    file:
      path: "{{ home_path }}/.vim/autoload"
      owner: "{{ ansible_user }}"
      group: wheel
      mode: 0755
      state: directory
    when: vim_path.stat.exists == False
  - name: Install vim-plug
    get_url:
      url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
      dest: "{{ home_path }}/.vim/autoload/plug.vim"
      mode: 0755
      owner: "{{ ansible_user }}"

  - name: Default shell to zsh
    shell: |
      chsh -s /usr/bin/zsh
      exec $SHELL -l
    args:
      executable: /bin/bash
