---
- name: "Set vars"
  set_fact:
    home_path: "/home/{{ ansible_user }}"

- name: "Install packages"
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - gcc
    - lua-devel
    - perl-ExtUtils-Embed
    - zlib-devel
    - bzip2
    - bzip2-devel
    - readline-devel
    - sqlite
    - sqlite-devel
    - openssl-devel
    - tmux
    - git
    - zsh
    - tree

- name: Clone repository
  git:
    repo: "https://github.com/{{ item.path }}"
    dest: "{{ home_path }}/{{ item.dir }}"
    force: yes
    update: yes
  become_user: "{{ ansible_user }}"
  with_items:
    - { path: "wting/autojump.git",     dir: "autojump" }
    - { path: "rainbow23/dotfiles.git", dir: "dotfiles" }
    - { path: "tmux-plugins/tpm",       dir: ".tmux/plugins/tpm" }
    - { path: "vim/vim",                dir: "vim8src" }
  notify:
    - Permission change to directories
    - Install autojump
    # - Create symlink

- block:
  - name: .bashrcディレクトリの存在チェック
    stat:
      path: "{{ home_path }}/.bashrc"
    register: bc
  - name: Delete file at .bashrc
    file:
      path: "{{ home_path }}/.bashrc"
      state: absent
    when: bc.stat.exists == True
  - name: Create symlink
    file:
      src: "{{ home_path }}/dotfiles/_{{ item }}"
      dest: "{{ home_path }}/.{{ item }}"
      owner: "{{ ansible_user }}"
      group: wheel
      mode: 0755
      state: link
    with_items:
      - vimrc
      - bashrc
      - zshrc
      - tmux.conf

- block:
  - name: Create vim-plug folder
    file:
      path: "{{ home_path }}/.vim/autoload"
      owner: "{{ ansible_user }}"
      group: wheel
      mode: 0755
      state: directory
  - name: Install vim-plug
    get_url:
      url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
      dest: "{{ home_path }}/.vim/autoload/plug.vim"
      mode: 0755
      owner: "{{ ansible_user }}"

- block:
  - name: Install pyenv from source
    shell: "curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash"
    become_user: "{{ ansible_user }}"
    args:
      executable: /bin/bash
  - name: add pyenv path to .bashrc and .zshrc
    shell: |
      echo -e '\n# pyenv' >> ~/.bashrc
      echo 'export PATH="$HOME/.pyenv/bin:$PATH"' >> ~/.bashrc
      echo 'eval "$(pyenv init -)"' >> ~/.bashrc
      echo 'eval "$(pyenv virtualenv-init -)"' >> ~/.bashrc
      echo -e '\n# pyenv' >> ~/.zshrc
      echo 'export PATH="$HOME/.pyenv/bin:$PATH"' >> ~/.zshrc
      echo 'eval "$(pyenv init -)"' >> ~/.zshrc
      echo 'eval "$(pyenv virtualenv-init -)"' >> ~/.zshrc
      source ~/.bashrc
      pyenv update
    become_user: "{{ ansible_user }}"
    args:
      executable: /bin/bash
  - name: .pyenvディレクトリの存在チェック
    stat:
      path: "{{ home_path }}/.pyenv/versions/3.6.0"
    register: py_path
  - name: Pyenv install specific python version
    shell: |
      pyenv install 3.6.0
    become_user: "{{ ansible_user }}"
    when: py_path.stat.exists == False
    args:
      executable: /bin/bash

- block:
  - name: Compile Vim
    shell: >
      cd /home/{{ ansible_user }}/vim8src && ./configure
      --enable-fail-if-missing
      --with-features=huge
      --disable-selinux
      --enable-luainterp
      --enable-perlinterp
      --enable-python3interp vi_cv_path_python3=/home/vagrant/.pyenv/versions/3.6.0/bin/python3.6
      --with-python3-config-dir=/home/vagrant/.pyenv/versions/3.6.0/lib/python3.6/config-3.6m-x86_64-linux-gnu
      --enable-cscope
      --enable-fontset
      --enable-multibyte
    become_user: "{{ ansible_user }}"
    args:
      executable: /bin/bash
  - name: Make & install Vim
    shell: >
      cd /home/{{ ansible_user }}/vim8src && make
      && make install
    args:
      executable: /bin/bash
